return {
  "hedyhli/outline.nvim",
  lazy = true,
  keys = { { "<leader>co", "<cmd>Outline<CR>", desc = "Outline Symbols", mode = { "n" } } },
  opts = {
    outline_window = {
      position = "right",
      split_command = nil,
      width = 25,
      relative_width = true,
      auto_close = false,
      auto_jump = true,
      jump_highlight_duration = 300,
      center_on_jump = true,
      show_numbers = false,
      show_relative_numbers = false,
      wrap = false,
      show_cursorline = true,
      hide_cursor = false,
      focus_on_open = true,
    },
    guides = {
      enabled = true,
      markers = {
        bottom = "└",
        middle = "├",
        vertical = "│",
      },
    },
    symbol_folding = {
      autofold_depth = 2,
      auto_unfold = {
        hovered = true,
        only = true,
      },
    },
    preview_window = {
      auto_preview = false,
      live = true,
    },
    keymaps = {
      goto_location = "<Cr>",
      hover_symbol = "K",
      peek_location = "P",
      toggle_preview = "T",
      goto_and_close = "O",
      fold_all = "F",
      unfold_all = "U",
      fold_reset = "R",
      rename_symbol = "r",
      code_actions = "a",
      down_and_jump = "<C-d>",
      up_and_jump = "<C-u>",
    },
  },
}
